backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - name: "categories" # Used in routes, e.g., /admin/collections/blog
    label: "category" # Used in the UI'
    identifier_field: name
    folder: "public/admin/data/categories" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    delete: false
    slug: "categories" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    extension: "json"
    summary: "Categories: Jashan Deol"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - name: categories
        label: Categories
        label_singular: category
        widget: list
        collapsed: true
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              field: { label: "Image", name: "image", widget: "image" },
            }

  - name: "Homapage images"
    label: "homapage images"
    label_singular: "homapage image"
    folder: "public/admin/data/heroImages"
    create: true
    slug: "heroImages"
    format: "json"
    extension: "json"
    summary: "Homepage Images"
    editor:
      preview: false
    feilds:
      - name: images
        label: images
        label_singular: image
        widget: list
        collapsed: true
        field: { label: "Image", name: "image", widget: "image" }
