backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - name: "categories" # Used in routes, e.g., /admin/collections/blog
    label: "category" # Used in the UI'
    identifier_field: name
    folder: "public/categories/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    delete: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    extension: "json"
    summary: "Categories: Jashan Deol"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - name: categories
        label: Categories
        label_singular: category
        title: categories
        widget: list
        collapsed: true
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              field: { label: "Image", name: "image", widget: "image" },
            }
