backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "Portfolio Images"
        name: "Portfolio Images"
        file: "public/admin/data/portfolio.json"
        fields:
          - name: images
            label: Images
            label_singular: Image
            widget: list
            collapsed: true
            field: { label: "Image", name: "image", widget: "image" }
      - label: "Projects"
        name: "Projects"
        file: "public/admin/data/projects.json"
        fields:
          - name: projects
            label: Projects
            label_singular: Project
            widget: list
            collapsed: true
            fields:
              - { label: "Project Name", name: "name", widget: "string" }
              - {
                  label: "Images",
                  name: "images",
                  widget: "list",
                  field: { label: "Image", name: "image", widget: "image" },
                }
              - {
                  label: "Project Details",
                  name: "details",
                  widget: "markdown",
                }
      - label: "homepage images"
        name: "homepage images"
        file: "public/admin/data/heroImages.json"
        fields:
          - name: images
            label: images
            widget: list
            collapsed: true
            field: { label: "Image", name: "image", widget: "image" }
      - label: "profile details"
        name: "profile details"
        file: "public/admin/data/profile.json"
        fields:
          - { label: "Header", name: "header", widget: "text" }
          - { label: "Details", name: "details", widget: "text" }
          - { label: "Phone Number", name: "phoneNumber", widget: "text" }
          - { label: "Email", name: "email", widget: "text" }
          - {
              label: "Instagram Username",
              name: "instaUsername",
              widget: "text",
            }
          - { label: "Image", name: "image", widget: "image" }
