backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assests/images"
public_folder: "/assests/images"

collections:
  - label: "Site Data"
    name: "site data"
    files:
      - label: "Portfolio Images"
        name: "Portfolio Images"
        file: "public/admin/data/portfolio.json"
        fields:
          - name: images
            label: Images
            label_singular: Image
            widget: list
            collapsed: true
            field: { label: "Image", name: "image", widget: "image" }
      - label: "Projects"
        name: "Projects"
        file: "public/admin/data/projects.json"
        fields:
          - name: projects
            label: Projects
            label_singular: Project
            widget: list
            collapsed: true
            fields:
              - { label: "Project Name", name: "name", widget: "string" }
              - {
                  label: "Project Details",
                  name: "details",
                  widget: "markdown",
                }
              - {
                  label: "Images",
                  name: "images",
                  widget: "list",
                  field: { label: "Image", name: "image", widget: "image" },
                }
      - label: "homepage images"
        name: "homepage images"
        file: "public/admin/data/heroImages.json"
        fields:
          - name: images
            label: images
            widget: list
            collapsed: true
            field: { label: "Image", name: "image", widget: "image" }
      - label: "profile details"
        name: "profile details"
        file: "public/admin/data/profile.json"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Details", name: "details", widget: "text" }
          - { label: "Phone Number", name: "phoneNumber", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - {
              label: "Instagram Username",
              name: "instaUsername",
              widget: "string",
            }
          - { label: "Facebook link", name: "fb", widget: "string" }
          - { label: "Twitter link", name: "twitter", widget: "string" }
          - { label: "LinkedIn link", name: "linkedIn", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
      - label: "About"
        name: "about"
        file: "public/admin/data/about.json"
        fields:
          - { label: "About Me", name: "aboutMe", widget: "markdown" }
          - { label: "Image", name: "aboutMeImage", widget: "image" }
          - {
              label: "Awards",
              name: "awards",
              widget: list,
              field: { label: "Award", name: "award", widget: "string" },
            }
          - {
              label: "Exhibitions",
              name: "exhibitions",
              widget: list,
              field:
                { label: "Exhibition", name: "exhibition", widget: "string" },
            }
          - name: Clients
            label: clients
            label_singular: client
            widget: list
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
      - label: "Testimonials"
        name: "testimonials"
        file: "public/admin/data/testimonials.json"
        fields:
          - name: testimonials
            label: Testimonials
            label_singular: Testimonial
            widget: list
            collapsed: true
            fields:
              - { label: "Client Name", name: "name", widget: "string" }
              - { label: "Feedback", name: "details", widget: "text" }
