# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Netlify deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.13.0
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.13.0
    - name: Build the site
      run: |
          npm i
          npm run build
          cp public/_redirects build/_redirects
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1.11
      with: 
        publish-dir: './build'
        production-branch: master
        deploy-message: '${{ github.event.head_commit.message }}'
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
        
        
        
        
        
        
        
        
        
        
      
